config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root 'rooms#index'
  get 'rooms/new' => 'rooms#new'
  get 'rooms/join' => 'rooms#join'
  get 'rooms/:room_name/lounge' => 'rooms#lounge', as: 'lounge'
  get 'rooms/:room_name/results' => 'rooms#results', as: 'results'
  # ajax通信用のurl
  get 'rooms/:room_name/loungeajax.html.erb' => 'rooms#loungeajax'
  get 'rooms/:room_name/showjax.html.erb' => 'rooms#showjax'
  get 'rooms/:room_name/picajax.html.erb' => 'rooms#picajax'
  get 'rooms/:room_name/myturnajax.html.erb' => 'rooms#myturnajax'
  post '/rooms' => 'rooms#create'
  post '/picpost' => 'picpost#create'
  get 'rooms/ajax'
  get 'rooms/:room_name' => 'rooms#show', as: 'room'
  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
    # belongs_to :user
    # belongs_to :room
    mount_uploader :image, ImageUploader
end

app/models/room.rb
class Room < ApplicationRecord
    validates :room_name, uniqueness: true
    # has_many :pictures
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rooms
  # has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
    added_attrs = [ :email, :username, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end
end

app/controllers/concerns/carrierwave_base64_uploader.rb
module CarrierwaveBase64Uploader
  extend ActiveSupport::Concern

  private

  def base64_conversion(uri_str, filename = "base64")
    image_data = split_base64(uri_str)
    image_data_string = image_data[:data]
    image_data_binary = Base64.decode64(image_data_string)

    temp_img_file = Tempfile.new(filename)
    temp_img_file.binmode
    temp_img_file << image_data_binary
    temp_img_file.rewind

    img_params = {:filename => "#{filename}.#{image_data[:extension]}", :type => image_data[:type], :tempfile => temp_img_file}
    ActionDispatch::Http::UploadedFile.new(img_params)
  end

  def split_base64(uri_str)
    if uri_str.match(%r{data:(.*?);(.*?),(.*)$})
      uri = Hash.new
      uri[:type] = $1
      uri[:encoder] = $2
      uri[:data] = $3
      uri[:extension] = $1.split('/')[1]
      return uri
    else
      return nil
    end
  end
end

app/controllers/picpost_controller.rb
class PicpostController < ApplicationController

    include CarrierwaveBase64Uploader

    def create
        picture = Picture.new(picture_params)
        theString64 = params[:picture][:image]
        # picture.image = base64_conversion(theString64, params[:picture][:time])
        picture.image = base64_conversion(theString64)
        picture.room_name = params[:picture][:room_name]
        picture.user_id = params[:picture][:user_id]
        picture.picname = params[:picture][:picname]
        picture.in_room_order = params[:picture][:in_room_order]
        picture.length = params[:picture][:length]
        picture.judge = params[:picture][:judge]
        picture.points = params[:picture][:points]
        picture.save
    end

    private
        def picture_params
            params.require(:picture).permit(:image, :user_id, :room_name, :picname, :in_room_order, :length, :judge, :points)
        end
end









# def create
#     require 'base64'
#     require 'stringio'
#     picture = Picture.new(picture_params)
#     theString64 = params[:picture][:testtext]
#     picture.image = Base64.decode64(theString64)
#     picture.test = params[:picture][:test]
#     picture.room_name = params[:picture][:room_name]
#     picture.user_id = params[:picture][:user_id]
#     # File.open('imageBase64.png', 'wb') do|f|
#     #     f.write(Base64.decode64(theString64))
#     # end
#     # picture.testtext = params[:picture][:testtext]
#     # @picture.image = params['picture']['image']
#     if picture.save
#         return
#     else
#         return
#     end
# end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    # require "active_support/time"
    # @user = User.find(current_user.id)
    # room = Room.where("created_time > ?", Time.new - 10)
    # Picture.where(room_name: room).delete_all
    # room.delete_all
  end

  def new
    @room = Room.new
    @user = User.find(current_user.id)
  end

  def create
    room = Room.new(room_params)
    User.find(current_user.id).update(roomname: params[:room][:room_name])
    room.user_id = current_user.id
    room.created_time = Time.new
    if room.save
      redirect_to lounge_path(params[:room][:room_name])
    else
      redirect_to :action => "new"
    end
  end

  def join
    @rooms = Room.all
    @user = User.find(current_user.id)
  end

  def lounge
    @room = Room.find_by(room_name: params[:room_name])
    @user = User.find(current_user.id)
  end

  def show
    @user = User.find(current_user.id)
    @room = Room.find_by(room_name: params[:room_name])
    @players = User.where(roomname: params[:room_name]).order(:randnum)
    @picture = Picture.new
    @images = Picture.where(room_name: params[:room_name])
  end

  # ajax通信用のアクション
  def loungeajax
    render layout: false
  end

  def picajax
    @room = Room.find_by(room_name: params[:room_name])
    @images = Picture.all
    render layout: false
  end
  def myturnajax
    @room = Room.find_by(room_name: params[:room_name])
    render layout: false
    # render :layout => 'forajax'
  end
  # def showjax
  #   render layout: false
  #   @user = User.find(current_user.id)
  # end

  def results
    @pictures = Picture.where(room_name: params[:room_name]).order(:id)
    @players = User.where(roomname: params[:room_name]).order(:randorder)
    @rankings = User.where(roomname: params[:room_name]).order(:score)
    @room = Room.find_by(room_name: params[:room_name])
  end


  private
    def room_params
      params.require(:room).permit(:room_name)
    end
    def picture_params
      params.require(:picture).permit(:image, :user_id, :room_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/picpost_helper.rb
module PicpostHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>dooble</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <%= link_to image_tag("title_logo.png", id:"header-title", class:"header-images"), root_path %>
    <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
    <div id="header-version">
      <p id="version-text">Ver.1.1</p>
    </div>
    <div id="header-info">
      <% if user_signed_in? %>
        <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
        <!-- *_path はUserモデルを作成したときに、
        deviseにより自動で作成されてますので、rake routesで確認できます -->
        <div class="header-links" id="header-message">
          こんにちは！ <strong id="header-username"><%= current_user.username %></strong> さん
        </div>
        <div class="header-links">
          <%= link_to(rooms_new_path) do %>
            <div class="link-boxes">
              <%= image_tag 'create_black.png', id: "new-link" %>
              <div class="mask">
                <div class="caption">new</div>
              </div>
            </div>
          <% end %>
        </div>
        <div class="header-links">
          <%= link_to(rooms_join_path) do %>
            <div class="link-boxes">
              <%= image_tag 'join_thin.png', id: "join-link" %>
              <div class="mask">
                <div class="caption" id="join-mask">join</div>
              </div>
            </div>
          <% end %>
        </div>
        <div class="header-links">
          <%= link_to(destroy_user_session_path, method: :delete) do %>
            <div class="link-boxes">
              <%= image_tag 'logout.png', id: "logout" %>
              <div class="mask">
                <div class="caption">bye</div>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
          <div class="header-links">
            さっそくとうろく！orログイン！
          </div>
          <div class="header-links">
            <%= link_to(new_user_session_path) do %>
              <div class="link-boxes">
                <%= image_tag 'login.png', id: "login" %>
                <div class="mask">
                  <div class="caption" id="before-logins">log<br>-in</div>
                </div>
              </div>
            <% end %>
          </div>
          <div class="header-links">
            <%= link_to(new_user_registration_path) do %>
              <div class="link-boxes">
                <%= image_tag 'signup.png', id: "signup" %>
                <div class="mask">
                  <div class="caption" id="before-logins">sign<br>-up</div>
                </div>
              </div>
            <% end %>
          </div>
          <%# link_to 'トップ', root_path %>
          <%# link_to "サインイン", new_user_registration_path %>
          <%# link_to "ログイン", new_user_session_path %>
          <%# link_to image_tag("new_link_white.png", id:"new-link", class:"header-images"), rooms_new_path %>
          <%# link_to 'ルーム参加', rooms_join_path %>
      <% end %>
    </div>
    <style>
      header{
        width: 100%;
        height: 5.5vw;
        background: #2ECFCA;
        display: flex;
        align-items: center;
      }
      #header-title{
        width: 16vw;
        height: auto;
        margin-left: 1.5vw;
      }
      #version-text{
        margin-top: 46%;
        font-size: 1.5vw;
      }
      #header-message{
        margin-right:3vw;
      }
      .header-links{
        /* margin-right: 1.5vw; */
      }
      .link-boxes{
        width: 5.5vw;
        height: 5.5vw;
        display: flex;
        justify-content: center;
        position: relative;
      }
      .link-boxes .caption {
        font-size: 2.5vw;
        /* text-align: center; */
        margin-left: 7%;
        margin-top: 9%;
        color: #fff;
      }
      .link-boxes .mask {
        width: 100%;
        height:	100%;
        position:	absolute;
        top: 0;
        left:	0;
        opacity: 0;
        text-align: center;
        background-color:	rgba(0,0,0,0.4);
        -webkit-transition:	all 0.2s ease;
        transition:	all 0.2s ease;
      }
      .link-boxes:hover .mask {
        opacity:		1;
      }
      #new-link{
        width: 4.5vw;
        height: 4.5vw;
        margin-top: 10%;
      }
      #join-link{
        width: 3.8vw;
        height: 4.7vw;
        margin-top: 7%;
      }
      #logout{
        width: 4vw;
        height: 4vw;
        margin-top: 13%;
      }
      #login{
        width: 4.3vw;
        height: 4.3vw;
        margin-top: 11%;
      }
      #signup{
        background-color: #FF4E62;
        padding: 8%;
        margin-top: 11%;
        height: 3.4vw;
        width: 3.4vw;
        border-radius: 20%;
        -moz-border-radius: 20%;
        -webkit-border-radius: 20%;
      }
      #before-logins{
        font-size: 2vw;
        line-height: 2vw;
        margin-top: 5%;
      }
      #join-mask{
        font-size: 2.3vw;
        margin-top: 9%;
      }
      #header-info{
        display: flex;
        align-items: center;
        margin-left: auto;
      }
      #header-username{
        font-size: 1.5vw;
      }


    </style>
  </header>

  <body>
    <%= yield %>
  </body>

  <footer>
    <%# <p>©nabe-chan All Rights Reserved.</p> %>
  </footer>
</html>

app/views/rooms/ajax.html.erb
<div class="ajaxReturn">
    <ul id="player-index">
        <% User.where(roomname: params[:room_name]).each do |player| %>
            <li class=<%= player.id %>><%= player.username %></li>
        <% end %>
    </ul>
</div>

app/views/rooms/index.html.erb
<div class="boxes" id="shiritori-box">
    <%= image_tag 'HDtopshiritori', id: "assets", width: "80%", height: "auto" %>
    <h1 id="omoikiri">思いっきり、えがこう。</h1>
</div>

<div class="boxes" id="enjoy-box">
    <%= image_tag 'bucket', id: "bucket", width: "60%", height: "auto" %>
    <%= image_tag 'pig', id: "pig", width: "10%", height: "auto" %>
    <%= image_tag 'raccoon', id: "raccoon", width: "9%", height: "auto" %>
    <%= image_tag 'drop-down', id: "drop-down", width: "17%", height: "auto" %>
    <%= image_tag 'rice', id: "rice", width: "10%", height: "auto" %>
    <h1 class="box-title" id="enjoy-title">「おえかき」を楽しもう！</h1>
    <p class="box-passage" id="enjoy-passage">
    「なべかき！」は、ともだちとオンラインで
    <br>&ensp;絵しりとりを遊べるアプリ！
    <br>&ensp;いっしょにハイスコアを目指す？
    <br>&ensp;MVPをめざしてたたかう？
    <br>&ensp;自分なりの楽しみ方を見つけに行こう！</p>
</div>

<div class="boxes" id="tips-box">
    <%= image_tag 'roller', id: "roller", width: "70%", height: "auto" %>
    <%= image_tag 'rocket', id: "rocket", width: "40%", height: "auto" %>
    <%= image_tag 'UFO', id: "UFO", width: "10%", height: "auto" %>
    <h1 id="tips-title" class="box-title">絵しりとりのコツ！</h1>
    <p class="box-passage tips-passage" id="tips-passage1">
    １.文字数をかせごう！
    <br>&ensp; 「なべかき！」では文字数がスコアになる！
    <br>&emsp; どんどんむずかしい言葉にチャレンジしよう！</p>
    <p class="box-passage tips-passage" id="tips-passage2">
    ２.自分の"味"を見つけよう！
    <br>&emsp; おえかきに答えはない！
    <br>&emsp; 自分のかく絵をすきになるところから始めよう！</p>
</div>

<div class="boxes" id="lets-start-box">
    <%= image_tag 'brush', id: "brush", width: "70%", height: "auto" %>
    <%= image_tag 'human', id: "human", width: "8%", height: "auto" %>
    <%= image_tag 'yamauchi', id: "yamauchi", width: "10%", height: "auto" %>
    <%= image_tag 'kiwi', id: "kiwi", width: "8%", height: "auto" %>
    <%= image_tag 'banana', id: "banana", width: "8%", height: "auto" %>
    <%= image_tag 'hamaie', id: "hamaie", width: "10%", height: "auto" %>
    <h1 id="last-title" class="box-title">さっそく始めよう！</h1>
    <div class="last-btns" id="btn1">
        <%= link_to(rooms_new_path, class:"last-link") do %>
            <div class="last btn-box btn">
            <h2 class="last-btn-text">ルームさくせい</h2>
            </div>
        <% end %>
    </div>
    <div class="last-btns" id="btn2">
        <%= link_to(rooms_join_path, class:"last-link") do %>
            <div class="last btn-box btn">
                <h2 class="last-btn-text">ルームさんか</h2>
            </div>
        <% end %>
    </div>

</div>
<div id='user_info' data-user_id="<%# @user.id %>" data-user_name="<%# @user.username %>">

app/views/rooms/join.html.erb
<div id='in_room' class="boo!"></div>
<div id='user_info' data-user_id="<%= @user.id %>" data-user_name="<%= @user.username %>">

    <form class="join-form-field">
        <h1 id="join-title">ルーム名入力！</h1>
        <input type="text" data-behavior="room_speaker" id="join-field">
    </form>

</div>

app/views/rooms/lounge.html.erb
<%= javascript_pack_tag 'lounge' %>
<div id='lounge' data-lounge="I'm_here"></div>
<div id='room_info' data-room_name="<%= @room.room_name %>" data-user_name="<%= @user.username %>" data-user_id="<%= @user.id %>"></div>


<h1 class="roomname"><%= "#{@room.room_name}" %></h1>
    <div id="start-btn-container">
    <% if @room.user_id == @user.id %>
    <button id="start-btn">ゲームスタート！</button>
    <% else %>
    <p><%= User.find(@room.user_id).username %>さんがホスト！</p>
    <br>
    <p>たいき中...</p>
    <% end %>
</div>


<div id="lounge-ajaxreload">
    <%# <h1>Ajax更新エリア</h1> =%>
</div>

app/views/rooms/loungeajax.html.erb
<div class="ajaxReturn">
    <div class="lounge-players">
        <% User.where(roomname: params[:room_name]).each do |player| %>
            <div class="player-card">
                <h2 class=<%= player.id %>><%= player.username %></h2>
            </div>
        <% end %>
    </div>
</div>

app/views/rooms/myturnajax.html.erb
<%# javascript_pack_tag 'picload' %>
<div class="ajaxReturn">
    <div id="can_you_draw" class="no"></div>
    <%# room = Room.where(room_name: params[:room_name])%>
    <% if @room.current_drawing_number == current_user.randorder %>
        <input type="text" id="picname_form" placeholder="ひらがなでにゅうりょく！" >
        <button id="turn-btn">OK!</button>
        <%#<div class="draw-kits">
            <button id="eraser">消しゴム</button>
            <button id="black">黒</button>
            <button id="yellow">黄色</button>
            <button id="blue">黄色</button>
            <button id="red">黄色</button>
        </div>%>
    <% else %>
    <h2><%= User.find_by(roomname: @room.room_name, randorder: @room.current_drawing_number).username %>さんがおえかき中...</h2>
    <% end %>
</div>

<%#<span id="wordcount">0文字</span>%>

app/views/rooms/new.html.erb
<div id='user_info' data-user_id="<%= @user.id %>" data-user_name="<%= @user.username %>">
<%= form_for @room do |f| %>
  <div class="new-room-form">
    <%# f.label :新規ルーム作成！ %>
    <%= f.text_field :room_name, :size => 70 %>
    <%= f.hidden_field :created_time, :value => Time.new %>
  <%= f.submit "ルームさくせい" , id: "create-room-btn"%>
  </div>
<% end %>

app/views/rooms/picajax.html.erb
<div class="pic-display">
    <% Picture.where(room_name: params[:room_name]).order(id: :DESC).each do |p| %>
        <div class="image-info">
            <%= image_tag p.image_url, class: "each-pic",  alt: "りろーどしてね！" if p.image? %>
            <p><%= p.in_room_order %>.<span id="words-circle"><%= "●"*p.picname.length %><span></p>
            <p>by【<%= User.find(p.user_id).username%>】</p>
        </div>
    <% end %>
    <div class="directions"><%= image_tag 'direction', id: "direction", width: "20%", height: "auto" %></div>
    <div class="directions"><h1 id="first_character"><%=Room.find_by(room_name: params[:room_name]).rand_first_character%></h1><span class="explanation" id="start-with">で始めて</span></div>
</div>

app/views/rooms/results.html.erb
<div class="results-top-box">
    <h1 id="results-roomname"><%= @room.room_name %></h1>
    <h1 id="total-score">全体スコア：<%= (@pictures.sum(:points) / @pictures.count).floor %>点</h1>
</div>

<% max_score = @pictures.maximum(:points) %>
<% mvp_id = @pictures.find_by(points: max_score).user_id %>
<div class="personal-box">
    <% @players.each do |p| %>
        <% if mvp_id == p.id %>
            <div class="personal-results">
                <p id="mvp"><%= p.username %>さんのスコア：
                <% userpics = Picture.where(room_name: p.roomname, user_id: p.id) %>
                <%= (userpics.sum(:points) / userpics.count).floor %>点 MVP!</p>
            </div>
        <% else %>
            <div class="personal-results">
                <p class="not-mvps"><%= p.username %>さんのスコア：
                <% userpics = Picture.where(room_name: p.roomname, user_id: p.id) %>
                <%= (userpics.sum(:points) / userpics.count).floor %>点</p>
            </div>
        <% end %>
    <% end %>
</div>


<div class="pic-display">
    <h1 id="first-chara-result"><%= @room.rand_first_character %></h1>
    <% @pictures.each do |p| %>
        <% if p.judge == 1 %>
                <div class="results-directions"><%= image_tag 'right-direction', id: "right-direction", class: "directions-img", width: "20%", height: "auto" %></div>
        <% else %>
                <div class="results-directions"><%= image_tag 'wrong-direction', id: "wrong-direction", class: "directions-img", width: "20%", height: "auto" %></div>
        <% end %>
        <div class="image-info">
            <%= image_tag p.image_url, class: "each-pic", size: "200x200" if p.image? %>
            <p><%= p.in_room_order %>. <%= p.picname %></p>
            <p><span class="results-points"><%= p.points %>点</span>  by<%= User.find(p.user_id).username%></p>
        </div>
    <% end %>
    <% last_picname = @pictures.last.picname %>
    <% last_character = last_picname[-1] %>
    <% if last_character ==  @room.rand_last_character %>
            <div class="results-directions"><%= image_tag 'right-direction', id: "right-direction", class: "directions-img", width: "20%", height: "auto" %></div>
    <% else %>
            <div class="results-directions"><%= image_tag 'wrong-direction', id: "wrong-direction", class: "directions-img", width: "20%", height: "auto" %></div>
    <% end %>
    <h1 id="last-chara-result"><%= @room.rand_last_character %></h1>
</div>

app/views/rooms/show.html.erb
<%# stylesheet_link_tag "show", :media => "all" %>
<%= javascript_pack_tag 'oekaki' %>
<%= javascript_pack_tag 'picload' %>

<div id="current_draw_number" class="<%= @room.current_drawing_number %>"></div>
<div id="current_rotation" class="<%= @room.rotation %>"></div>
<div id="th_turn" class="<%= @room.th_turn %>"></div>

<div id="rand_first_character" class="<%= @room.rand_first_character %>"></div>
<div id="rand_last_character" class="<%= @room.rand_last_character %>"></div>
<div id='user_info' data-room_name="<%= @room.room_name %>" data-room_id="<%= @room.id %>" data-player_amount="<%= @players.count %>" data-current_rotation="<%= @room.rotation %>" data-user_name="<%= @user.username %>" data-user_id="<%= @user.id %>" data-randorder="<%= @user.randorder %>"></div>

<% player_amount = @players.count %>
<% if %>
<% player_amount < 3 %>
<% max_turn = player_amount*3 %>
<% elsif %>
<% player_amount < 5 %>
<% max_turn = player_amount*2 %>
<% else %>
<% max_turn = player_amount %>
<% end %>

<div class="main-container">
    <div class="left-container">
        <div class="other-traits">
            <div id="count-box">
                <h1 id="count-down">60</h1>
            </div>
            <%#<button id="black">色</button>
            <button id="width">幅</button>%>
            <button id="clear-btn">リセット</button>
        </div>
            <%#<div class="canvas-btns">
                <button class="canvas-btn" id="widthA"><div class="btn-circle-text"><p class="circle">●</p></div></button>
                <button class="canvas-btn" id="widthB"><div class="btn-circle-text"><p class="circle">●</p></div></button>
                <button class="canvas-btn" id="widthC"><div class="btn-circle-text"><p class="circle">●</p></div></button>

                <button class="canvas-btn" id="eraser"></button>

                <button class="canvas-btn" id="red"></button>
                <button class="canvas-btn" id="blue"></button>
                <button class="canvas-btn" id="green"></button>
                <button class="canvas-btn" id="yellow"></button>
            </div>%>
            <div class="main-canvas">
                <canvas id="draw-area" width="400px" height="400px"></canvas>
            </div>
        <div id="btn-reload">
        </div>
    </div>
    <div class="right-container">
        <div class="top-right-box">
            <div id="turn-count-box">
                <span class="explanation">あと</span><h1 id="turn-count"><%= max_turn - @room.th_turn + 1 %></h1><span class="explanation">ターンで</span>
            </div>
            <div class="last-chara-box">
                <div id="last_picname" class="<%= @room.last_picname %>"></div>
                <h1 id="last-character">「<%= @room.rand_last_character %>」</h1><span class="explanation">で終わろう！</span>
            </div>
        </div>
        <div class="middle-right-box">
            <div id="player-index">
                <% @players.each do |player| %>
                    <div class="current-players" id="<%=player.randorder%>th-player"><%= player.randorder+1 %>.<%= player.username %></div>
                <% end %>
            </div>
        </div>
        <div id="picreload">
                <%# 画像更新ajax =%>
        </div>
    </div>
</div>

app/views/rooms/showjax.html.erb
<div class="ajaxReturn">
    <ul id="in-room-players">
        <% User.where(roomname: params[:room_name]).each do |player| %>
            <li class="<%= player.id %>"><%= player.username %></li>
        <% end %>
    </ul>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>